spring:
  redis:
    #单机Redis配置
    host: 192.168.154.129
    port: 6379
    password: foobared123

    #集群版Redis配置
    #cluster:
      #获取失败,最大重定向次数
      #max-redirects: 3
      #nodes:
      #  - 192.168.154.129:7001
      #  - 192.168.154.129:7002
      #  - 192.168.154.129:7003
      #  - 192.168.154.129:7004
      #  - 192.168.154.129:7005
      #  - 192.168.154.129:7006
    #password: 123456

    #SpringBoot2.x版本中,默认使用Lettuce;SpringBoot1.5版本默认使用Jedis
    lettuce:
      pool:
      #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
      #连接池中的最大空闲连接
        max-idle: 1000
      #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: 1000
      #连接池中的最小空闲连接
        min-idle: 0
    timeout: 3000