spring:
  redis:
    host: 120.55.40.51
    port: 6379
    #密码.没有设置Redis连接密码可以不配置
    password: foobared
    #SpringBoot2.x版本中,默认使用Lettuce;SpringBoot1.5版本默认使用Jedis
    lettuce:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 1000
        #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: 1000
        #连接池中的最小空闲连接
        min-idle: 0
    timeout: 3000